// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfeA6Ifn0xp0_rYfirSOIO9MBF7tWH8gs',
    appId: '1:827038614081:web:f32688c5eeaccf84f93cc0',
    messagingSenderId: '827038614081',
    projectId: 'flutter-stripe-91cd8',
    authDomain: 'flutter-stripe-91cd8.firebaseapp.com',
    storageBucket: 'flutter-stripe-91cd8.appspot.com',
    measurementId: 'G-01537XLEKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPpB3dMcwcR-z6SQM-DEPfEoCcha2Bk4c',
    appId: '1:827038614081:android:6462b90d86027ff1f93cc0',
    messagingSenderId: '827038614081',
    projectId: 'flutter-stripe-91cd8',
    storageBucket: 'flutter-stripe-91cd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ0IBOy2a3Ddm-HRjNjl6FLpnDfPq_JvA',
    appId: '1:827038614081:ios:1a4becf1a1206ef9f93cc0',
    messagingSenderId: '827038614081',
    projectId: 'flutter-stripe-91cd8',
    storageBucket: 'flutter-stripe-91cd8.appspot.com',
    iosClientId: '827038614081-rdpd4n5n1u6kk5i8plnhdinh18s5qhfq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStripeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ0IBOy2a3Ddm-HRjNjl6FLpnDfPq_JvA',
    appId: '1:827038614081:ios:26c3bc418d36fdaff93cc0',
    messagingSenderId: '827038614081',
    projectId: 'flutter-stripe-91cd8',
    storageBucket: 'flutter-stripe-91cd8.appspot.com',
    iosClientId: '827038614081-h4oa7k3cnmohqtomqo8kq42rbu8sfre7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStripeApp.RunnerTests',
  );
}
